# Generated by Django 2.1 on 2018-09-20 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.CharField(blank=True, max_length=10)),
                ('room', models.CharField(blank=True, max_length=10)),
                ('object_type', models.CharField(blank=True, max_length=2)),
                ('status', models.CharField(blank=True, max_length=10)),
                ('document', models.ImageField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
