# Generated by Django 2.1 on 2018-10-16 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoogleGlass', '0002_auto_20181016_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='todo',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
