# Generated by Django 2.1 on 2018-10-16 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoogleGlass', '0003_document_todo'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='edit_status_to',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
