# Generated by Django 2.1 on 2018-09-25 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoogleGlass', '0003_auto_20180925_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.ImageField(null=True, upload_to='documents/'),
        ),
    ]
