# Generated by Django 2.1 on 2018-09-25 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoogleGlass', '0004_auto_20180925_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.ImageField(default='ducky.jpg', upload_to='documents/'),
        ),
    ]
