# Generated by Django 2.1 on 2018-10-17 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GoogleGlass', '0005_document_object_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='object_type',
            new_name='obj_type',
        ),
    ]
