# Generated by Django 2.1 on 2018-10-17 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GoogleGlass', '0006_auto_20181017_0918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='obj_type',
        ),
    ]
