# Generated by Django 2.1 on 2018-10-17 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoogleGlass', '0007_remove_document_obj_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='object_type',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
