# Generated by Django 2.1 on 2018-10-06 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoogleGlass', '0007_auto_20180925_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(blank=True, max_length=10)),
                ('object_type', models.CharField(blank=True, max_length=10)),
                ('status', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.ImageField(default='documents/None/No_images.jpg/', upload_to='documents/'),
        ),
    ]
