# Generated by Django 2.1 on 2018-10-17 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoogleGlass', '0008_document_object_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='object_id',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
